### ISSUE TITLE
Problema de alinhamento em tabela

### ISSUE THREAD

**Issue by helioh3** [devitools/quasar#20]
Há um problema de alinhamento, geralmente no penúltimo item de tabelas que são montadas com o `fieldIsBuiltin(ExemploSchema.provideBuiltin())`

**Comment by iguit0** [comment]
@helioh3 Tem um exemplo com evidências do caso ?

**Comment by helioh3** [comment]
> @helioh3 Tem um exemplo com evidências do caso ?

Igão, não consegui encontrar aqui o problema que descrevi nessa Issue. Foi mal! :/
